VERTICAL_BORDER_SYMBOL = '|'
HORIZONTAL_BORDER_SYMBOL = '-'
BACKGROUND_SYMBOL = ' '
LINE_SYMBOL = 'x'
RECTANGLE_SYMBOL = 'x'

CANVAS_COMMAND = 'c'
LINE_COMMAND = 'l'
RECTANGLE_COMMAND = 'r'
BUCKETFILL_COMMAND = 'b'

SYMBOLS = [
    VERTICAL_BORDER_SYMBOL,
    HORIZONTAL_BORDER_SYMBOL,
    LINE_SYMBOL,
    RECTANGLE_SYMBOL
]
COMMANDS = [
    CANVAS_COMMAND,
    LINE_COMMAND,
    RECTANGLE_COMMAND,
    BUCKETFILL_COMMAND
]